name: Bot Apuestas

on:
  schedule:
    # Se ejecuta cada 6 horas (para cuidar tus 500 llamadas mensuales gratis)
    # Cron syntax: minuto hora dia mes dia_semana
    - cron: '0 */2 * * *' 
  workflow_dispatch: # Permite ejecutarlo manualmente con un botón para probar

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install -r requirements.txt

      - name: Ejecutar Bot
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python main.py